name: Run tests for PRs and pushes into master for app

on:
  push:
    branches: 
      - master
    paths-ignore:
      - 'tests/tools/**'
  pull_request:
    branches: 
      - master
    paths-ignore:
      - 'tests/tools/**'

jobs:
  runner-job:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'

      - name: Install pipenv
        run: pip3 install pipenv

      - name: Create Pipenv environment
        run: pipenv install --python=python3 --keep-outdated --ignore-pipfile

      - name: Run unit tests
        run: pipenv run py.test --ignore=tests/tools tests